### ISSUE TITLE
BUG : Room ID and Username Validation Allows Whitespace Input

### ISSUE THREAD

**Issue by Rudrajiii** [sahilatahar/Code-Sync#22]
## **Describe the bug**
Room ID and Username fields were allowing whitespace characters to be counted toward the minimum length requirement. This allowed users to join with only spaces in the Room ID and Username fields, bypassing the intended character validation.
## Here is the demo ~

https://github.com/user-attachments/assets/488df5e8-a1be-49d2-863b-7f91f86d17a7

**To Reproduce**

- Go to the room creation/joining page.
- Enter a Room ID with 5 spaces and a Username with 3 spaces.
- Attempt to join or create a room.
- Notice that the form is submitted successfully, despite only spaces being entered.

**Expected behavior**
The Room ID should require at least 5 non-space characters, and the Username should require at least 3 non-space characters. Spaces should not be counted toward the character minimum for either field.

**Additional context**
To resolve this issue, I added a trim() function to remove leading and trailing whitespace from the Room ID and Username fields before validation, ensuring that only non-space characters are counted in the length check.

**Comment by sahilatahar** [comment]
@Rudrajiii Great. Thanks for fixing it.
