### ISSUE TITLE
ERROR - Syntax Highlighting not available for this language

### ISSUE THREAD

**Issue by alexsoin** [sahilatahar/Code-Sync#7]
When creating a file with any extensions other than `js`, an error appears `Syntax Highlighting not available for this language` :

![изображение](https://github.com/sahilatahar/Code-Sync/assets/3787132/b516a53d-6078-4271-87da-f0ee00de4162)

_(checked with `ts`, `php`, `cs` extensions)_

At the same time, the compilation of the code occurs without problems:

![изображение](https://github.com/sahilatahar/Code-Sync/assets/3787132/6784db3e-40a4-410c-a17c-b8ca35d7c13c)

**Comment by sahilatahar** [comment]
@alexsoin Thanks for creating the issue. I have checked it, and syntax highlighting for PHP and C# is not applying automatically, but syntax highlights are available for those languages. You can change the editor language manually from `settings > Editor Language` for now. I will fix this issue very soon.

**Comment by alexsoin** [comment]
![ezgif-7-71ba741790](https://github.com/sahilatahar/Code-Sync/assets/3787132/79c1fc3d-b6da-4e91-bb9f-f2787d1353b6)

**Comment by sahilatahar** [comment]
@alexsoin Thank you for reporting this issue. I've addressed it by implementing a custom mapping solution to fix the syntax highlighting problem. If you encounter any further issues or have additional feedback, please don't hesitate to let me know. Your input is greatly appreciated!
